#!/usr/bin/env bash
# Submit the Stage 2 neural Transformer prepare/train/score job.
# Usage: scripts/calculco/submit_phase8_p0_neural_training.sh [development|final]
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
project_home="${PROJECT_HOME:-$(cd "$script_dir/../.." && pwd)}"
mode="${1:-development}"

if [[ "$mode" != "development" && "$mode" != "final" ]]; then
  echo "Usage: $0 [development|final]" >&2
  exit 2
fi

mkdir -p "$project_home/scripts/calculco/logs"

job_env="$script_dir/phase8_p0_neural_training_job.env"
cat >"$job_env" <<EOF
# Generated by submit_phase8_p0_neural_training.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')
NEURAL_STAGES="prepare train score"
NEURAL_MODE=$mode
NEURAL_SEED=20260617
NEURAL_TOP_K=1,3,5,10
NEURAL_MAX_SEQUENCE_LENGTH=128
NEURAL_SHARD_COUNT=8
NEURAL_BATCH_RANKING_GROUPS=64
NEURAL_MAX_EPOCHS=30
NEURAL_EARLY_STOPPING_PATIENCE=3
DUCKDB_THREADS=8
DUCKDB_MEMORY_LIMIT=24GB
EOF

echo "Wrote $job_env (mode=$mode)"
oarsub -O "$project_home/scripts/calculco/logs/rm_phase8_p0_neural_training_%jobid%.out" \
       -E "$project_home/scripts/calculco/logs/rm_phase8_p0_neural_training_%jobid%.err" \
       -S "$script_dir/phase8_p0_neural_training.sh"
