#!/usr/bin/env bash
# Submit GNN/fusion development training or one explicitly chosen final score.
#
# Usage:
#   scripts/calculco/submit_phase8_p0_gnn_training.sh development
#   scripts/calculco/submit_phase8_p0_gnn_training.sh final score-fusion

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
project_home="${PROJECT_HOME:-$(cd "$script_dir/../.." && pwd)}"
mode="${1:-development}"
stage="${2:-}"
: "${WORK_SCRATCH:?Export WORK_SCRATCH before submit (OAR jobs do not inherit interactive shell exports)}"

case "$WORK_SCRATCH" in
  /path|/path/*)
    echo "WORK_SCRATCH looks like a documentation placeholder: $WORK_SCRATCH" >&2
    exit 2
    ;;
esac

if [[ "$mode" == "development" ]]; then
  if [[ -n "$stage" ]]; then
    echo "Development submission does not accept a stage override." >&2
    exit 2
  fi
  stages="train-gnn score-gnn train-fusion score-fusion"
  final_confirmation=""
elif [[ "$mode" == "final" ]]; then
  if [[ "$stage" != "score-gnn" && "$stage" != "score-fusion" ]]; then
    echo "Final usage: $0 final {score-gnn|score-fusion}" >&2
    exit 2
  fi
  : "${GNN_FINAL_SCORE_CONFIRM:?Confirm the one-shot final run before submit}"
  if [[ "$GNN_FINAL_SCORE_CONFIRM" != "I_UNDERSTAND_ONE_SHOT" ]]; then
    echo "GNN_FINAL_SCORE_CONFIRM must equal I_UNDERSTAND_ONE_SHOT." >&2
    exit 2
  fi
  stages="$stage"
  final_confirmation="$GNN_FINAL_SCORE_CONFIRM"
else
  echo "Usage: $0 {development|final [score-gnn|score-fusion]}" >&2
  exit 2
fi

env_file="$script_dir/phase8_p0_gnn_training_job.env"
cat >"$env_file" <<EOF
# Generated by submit_phase8_p0_gnn_training.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')
WORK_SCRATCH=$WORK_SCRATCH
GNN_MODE=$mode
GNN_STAGES="$stages"
GNN_SEED=${GNN_SEED:-20260617}
GNN_TOP_K=${GNN_TOP_K:-1,3,5,10}
GNN_FOLD_COUNT=${GNN_FOLD_COUNT:-5}
GNN_SHARD_COUNT=${GNN_SHARD_COUNT:-256}
GNN_BATCH_RANKING_GROUPS=${GNN_BATCH_RANKING_GROUPS:-32}
GNN_MAX_EPOCHS=${GNN_MAX_EPOCHS:-30}
GNN_EARLY_STOPPING_PATIENCE=${GNN_EARLY_STOPPING_PATIENCE:-3}
GNN_DEVICE=${GNN_DEVICE:-cuda}
GNN_FINAL_SCORE_CONFIRM=$final_confirmation
DUCKDB_THREADS=${DUCKDB_THREADS:-8}
DUCKDB_MEMORY_LIMIT=${DUCKDB_MEMORY_LIMIT:-24GB}
EOF
chmod 600 "$env_file"

mkdir -p "$project_home/scripts/calculco/logs"
echo "Wrote protected job settings to $env_file"
oarsub \
  -O "$project_home/scripts/calculco/logs/rm_phase8_p0_gnn_training_%jobid%.out" \
  -E "$project_home/scripts/calculco/logs/rm_phase8_p0_gnn_training_%jobid%.err" \
  -S "$script_dir/phase8_p0_gnn_training.sh"
