#!/usr/bin/env bash
# Submit the CPU GNN cache-preparation job after a storage-capacity review.
#
# Usage:
#   GNN_CROSSFIT_MIN_FREE_GIB=<reviewed-value> \
#     scripts/calculco/submit_phase8_p0_gnn_prepare.sh

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
project_home="${PROJECT_HOME:-$(cd "$script_dir/../.." && pwd)}"
: "${GNN_CROSSFIT_MIN_FREE_GIB:?Set the reviewed minimum free GiB before submit}"
: "${WORK_SCRATCH:?Export WORK_SCRATCH before submit (OAR jobs do not inherit interactive shell exports)}"

case "$WORK_SCRATCH" in
  /path|/path/*)
    echo "WORK_SCRATCH looks like a documentation placeholder: $WORK_SCRATCH" >&2
    exit 2
    ;;
esac

env_file="$script_dir/phase8_p0_gnn_prepare_job.env"
cat >"$env_file" <<EOF
# Generated by submit_phase8_p0_gnn_prepare.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')
WORK_SCRATCH=$WORK_SCRATCH
GNN_MODE=development
GNN_SEED=${GNN_SEED:-20260617}
GNN_TOP_K=${GNN_TOP_K:-1,3,5,10}
GNN_FOLD_COUNT=${GNN_FOLD_COUNT:-5}
GNN_SHARD_COUNT=${GNN_SHARD_COUNT:-256}
GNN_DEVICE=cpu
GNN_CROSSFIT_MIN_FREE_GIB=$GNN_CROSSFIT_MIN_FREE_GIB
DUCKDB_THREADS=${DUCKDB_THREADS:-4}
DUCKDB_MEMORY_LIMIT=${DUCKDB_MEMORY_LIMIT:-128GB}
DUCKDB_MAX_TEMP_DIR_SIZE=${DUCKDB_MAX_TEMP_DIR_SIZE:-400GB}
EOF
chmod 600 "$env_file"

mkdir -p "$project_home/scripts/calculco/logs"
echo "Wrote protected job settings to $env_file"
oarsub \
  -O "$project_home/scripts/calculco/logs/rm_phase8_p0_gnn_prepare_%jobid%.out" \
  -E "$project_home/scripts/calculco/logs/rm_phase8_p0_gnn_prepare_%jobid%.err" \
  -S "$script_dir/phase8_p0_gnn_prepare.sh"
