#!/usr/bin/env bash
# Submit the Phase 8 P0 model-ready chain with durable env propagation.
#
# OAR `-S` jobs run in a clean environment and ignore login-shell exports, so
# knobs like PHASE8_P0_START_AT never reached the worker before. This wrapper
# writes them to a gitignored job env file that phase8_p0_model_ready.sh sources.
#
# Usage examples:
#   scripts/calculco/submit_phase8_p0_model_ready.sh                 # full chain
#   scripts/calculco/submit_phase8_p0_model_ready.sh subgraphs       # resume
#   SUBGRAPH_JOIN_SHARDS=16 \
#     scripts/calculco/submit_phase8_p0_model_ready.sh subgraphs
#
# Override any value via environment at submit time; defaults match the worker.

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
: "${PROJECT_HOME:=$HOME/ResearchModule}"

start_at="${1:-${PHASE8_P0_START_AT:-training}}"
if [[ "$start_at" != "training" && "$start_at" != "subgraphs" ]]; then
  echo "Usage: $0 [training|subgraphs]" >&2
  exit 2
fi

: "${SUBGRAPH_BATCHES:=8}"
: "${SUBGRAPH_JOIN_SHARDS:=8}"
: "${SUBGRAPH_EDGE_THREADS:=1}"
: "${DUCKDB_MEMORY_LIMIT:=10GB}"
: "${CANDIDATE_TOKEN_STRATEGY:=rxnorm_or_atc}"
: "${PHASE8_P0_FEATURE_VERSION:=temporal-features-v2}"
: "${PHASE8_P0_RUN_FEATURES:=auto}"

env_file="$script_dir/phase8_p0_model_ready_job.env"
cat >"$env_file" <<EOF
# Generated by submit_phase8_p0_model_ready.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')
PHASE8_P0_START_AT=$start_at
PHASE8_P0_RUN_FEATURES=$PHASE8_P0_RUN_FEATURES
PHASE8_P0_FEATURE_VERSION=$PHASE8_P0_FEATURE_VERSION
CANDIDATE_TOKEN_STRATEGY=$CANDIDATE_TOKEN_STRATEGY
SUBGRAPH_BATCHES=$SUBGRAPH_BATCHES
SUBGRAPH_JOIN_SHARDS=$SUBGRAPH_JOIN_SHARDS
SUBGRAPH_EDGE_THREADS=$SUBGRAPH_EDGE_THREADS
DUCKDB_MEMORY_LIMIT=$DUCKDB_MEMORY_LIMIT
EOF

mkdir -p "$script_dir/logs"
echo "Wrote $env_file"
cat "$env_file"

oarsub -O "$PROJECT_HOME/scripts/calculco/logs/rm_phase8_p0_model_ready_%jobid%.out" \
       -E "$PROJECT_HOME/scripts/calculco/logs/rm_phase8_p0_model_ready_%jobid%.err" \
       -S "$PROJECT_HOME/scripts/calculco/phase8_p0_model_ready.sh"
