#!/usr/bin/env bash
# Submit Milestone 8B graph-aware ablation evaluation with durable env propagation.
#
# Usage examples:
#   scripts/calculco/submit_graph_ablation.sh development
#   scripts/calculco/submit_graph_ablation.sh final
#   MILESTONE8B_CONDITION_TOKENS=condition:sepsis \
#     scripts/calculco/submit_graph_ablation.sh development
#
# The selected env is written to scripts/calculco/milestone8b_job.env
# (gitignored) and sourced inside graph_ablation.sh by the OAR worker.

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
: "${PROJECT_HOME:=$HOME/ResearchModule}"

mode="${1:-development}"
if [[ "$mode" != "development" && "$mode" != "final" ]]; then
  echo "Usage: $0 [development|final]" >&2
  exit 2
fi

frozen_selection=0
if [[ "$mode" == "final" ]]; then
  frozen_selection=1
  if [[ ! -f "$PROJECT_HOME/reports/milestone8b_frozen_selection.json" ]]; then
    echo "ERROR: missing reports/milestone8b_frozen_selection.json" >&2
    echo "Run development graph ablation and freeze validation choices first." >&2
    exit 1
  fi
fi

: "${MILESTONE8B_TOP_K:=1,3,5,10}"
: "${MILESTONE8B_CONDITION_TOKENS:=}"

env_file="$script_dir/milestone8b_job.env"
cat >"$env_file" <<EOF
# Generated by submit_graph_ablation.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')
MILESTONE8B_MODE=$mode
MILESTONE8B_TOP_K=$MILESTONE8B_TOP_K
MILESTONE8B_FROZEN_SELECTION=$frozen_selection
MILESTONE8B_CONDITION_TOKENS=$MILESTONE8B_CONDITION_TOKENS
EOF

mkdir -p "$script_dir/logs"
echo "Wrote $env_file"
cat "$env_file"

oarsub -O "$PROJECT_HOME/scripts/calculco/logs/rm_graph_ablation_%jobid%.out" \
       -E "$PROJECT_HOME/scripts/calculco/logs/rm_graph_ablation_%jobid%.err" \
       -S "$PROJECT_HOME/scripts/calculco/graph_ablation.sh"
