#!/usr/bin/env bash
# Submit Phase 8 P0 Milestone 8 + 8B development gates in one OAR job.
#
# Usage:
#   scripts/calculco/submit_phase8_p0_graph_gates.sh

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
: "${PROJECT_HOME:=$HOME/ResearchModule}"

: "${MILESTONE8B_TOP_K:=1,3,5,10}"
: "${MILESTONE8B_CONDITION_TOKENS:=}"
: "${MILESTONE8B_ALLOW_DEVELOPMENT_MILESTONE7_REFERENCE:=1}"

env_file="$script_dir/phase8_p0_milestone8b_job.env"
cat >"$env_file" <<EOF
# Generated by submit_phase8_p0_graph_gates.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')
MILESTONE8B_MODE=development
MILESTONE8B_TOP_K=$MILESTONE8B_TOP_K
MILESTONE8B_FROZEN_SELECTION=0
MILESTONE8B_CONDITION_TOKENS=$MILESTONE8B_CONDITION_TOKENS
MILESTONE8B_ALLOW_DEVELOPMENT_MILESTONE7_REFERENCE=$MILESTONE8B_ALLOW_DEVELOPMENT_MILESTONE7_REFERENCE
EOF

mkdir -p "$script_dir/logs"
echo "Wrote $env_file"
cat "$env_file"

oarsub -O "$PROJECT_HOME/scripts/calculco/logs/rm_phase8_p0_graph_gates_%jobid%.out" \
       -E "$PROJECT_HOME/scripts/calculco/logs/rm_phase8_p0_graph_gates_%jobid%.err" \
       -S "$PROJECT_HOME/scripts/calculco/phase8_p0_graph_gates.sh"
