#!/usr/bin/env bash
# Submit Milestone 7 baseline evaluation with durable env propagation.
#
# Usage examples:
#   scripts/calculco/submit_evaluate_baselines.sh development
#   scripts/calculco/submit_evaluate_baselines.sh final
#   MILESTONE7_BASELINES=random,global_popularity,condition_popularity,linear \
#     scripts/calculco/submit_evaluate_baselines.sh development
#
# The selected env is written to scripts/calculco/milestone7_job.env (gitignored)
# and sourced inside evaluate_baselines.sh by the OAR worker.

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
: "${PROJECT_HOME:=$HOME/ResearchModule}"

mode="${1:-development}"
if [[ "$mode" != "development" && "$mode" != "final" ]]; then
  echo "Usage: $0 [development|final]" >&2
  exit 2
fi

frozen_selection=0
if [[ "$mode" == "final" ]]; then
  frozen_selection=1
  if [[ ! -f "$PROJECT_HOME/reports/milestone7_frozen_selection.json" ]]; then
    echo "ERROR: missing reports/milestone7_frozen_selection.json" >&2
    echo "Freeze validation choices before submitting final evaluation." >&2
    exit 1
  fi
fi

: "${MILESTONE7_TOP_K:=1,3,5,10}"
: "${MILESTONE7_BASELINES:=random,global_popularity,condition_popularity,linear,xgboost}"
: "${MILESTONE7_CONDITION_TOKENS:=}"

env_file="$script_dir/milestone7_job.env"
cat >"$env_file" <<EOF
# Generated by submit_evaluate_baselines.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')
MILESTONE7_MODE=$mode
MILESTONE7_TOP_K=$MILESTONE7_TOP_K
MILESTONE7_FROZEN_SELECTION=$frozen_selection
MILESTONE7_BASELINES=$MILESTONE7_BASELINES
MILESTONE7_CONDITION_TOKENS=$MILESTONE7_CONDITION_TOKENS
EOF

mkdir -p "$script_dir/logs"
echo "Wrote $env_file"
cat "$env_file"

oarsub -O "$PROJECT_HOME/scripts/calculco/logs/rm_eval_%jobid%.out" \
       -E "$PROJECT_HOME/scripts/calculco/logs/rm_eval_%jobid%.err" \
       -S "$PROJECT_HOME/scripts/calculco/evaluate_baselines.sh"
