#!/usr/bin/env bash
# Submit the CPU-only Phase 8 P0 structured recovery experiment through OAR.
# Usage: scripts/calculco/submit_phase8_p0_gate_recovery.sh [development|final]

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
: "${PROJECT_HOME:=$HOME/ResearchModule}"

mode="${1:-development}"
if [[ "$mode" != "development" && "$mode" != "final" ]]; then
  echo "Usage: $0 [development|final]" >&2
  exit 2
fi

if [[ "$mode" == "final" && ! -f "$PROJECT_HOME/reports/phase8_p0_gate_recovery_selection.json" ]]; then
  echo "ERROR: a frozen passing development selection is required for final mode." >&2
  exit 1
fi

: "${GATE_RECOVERY_TOP_K:=1,3,5,10}"
: "${GATE_RECOVERY_FOLD_COUNT:=3}"
: "${GATE_RECOVERY_SEED:=20260617}"

env_file="$script_dir/phase8_p0_gate_recovery_job.env"
cat >"$env_file" <<EOF
# Generated by submit_phase8_p0_gate_recovery.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')
GATE_RECOVERY_MODE=$mode
GATE_RECOVERY_TOP_K=$GATE_RECOVERY_TOP_K
GATE_RECOVERY_FOLD_COUNT=$GATE_RECOVERY_FOLD_COUNT
GATE_RECOVERY_SEED=$GATE_RECOVERY_SEED
EOF

mkdir -p "$script_dir/logs"
echo "Wrote $env_file"

oarsub -O "$PROJECT_HOME/scripts/calculco/logs/rm_phase8_p0_gate_recovery_%jobid%.out" \
       -E "$PROJECT_HOME/scripts/calculco/logs/rm_phase8_p0_gate_recovery_%jobid%.err" \
       -S "$PROJECT_HOME/scripts/calculco/phase8_p0_gate_recovery.sh"
